use std::process::exit;

fn main() {
    println!("Expected failure");
    exit(1);
}
